<div class="space-y-6" x-data="dailyPostIdeas()">
    <!-- Header Card -->
    <div class="bg-white rounded-3xl shadow-sm border border-gray-100 p-6 md:p-8">
        <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
            <div>
                <p class="text-sm uppercase tracking-[0.4em] text-green-500">Daily Post Ideas</p>
                <h1 class="text-3xl md:text-4xl font-semibold text-gray-900 mt-2">
                    Generate Tweet Ideas
                </h1>
                @if ($hasCachedIdeas)
                    <p class="text-gray-500 mt-2 text-sm md:text-base">
                        <i class="bx bx-check-circle mr-1 text-green-600"></i>
                        Ideas loaded from cache for today
                    </p>
                @elseif($autoGenerated)
                    <p class="text-gray-500 mt-2 text-sm md:text-base">
                        <i class="bx bx-refresh mr-1 text-blue-600"></i>
                        Auto-generated for today
                    </p>
                @elseif(empty($topic) || empty($niche))
                    <p class="text-gray-500 mt-2 text-sm md:text-base">
                        <i class="bx bx-info-circle mr-1 text-orange-600"></i>
                        Set your preferences to get started
                    </p>
                @else
                    <p class="text-gray-500 mt-2 text-sm md:text-base">
                        <i class="bx bx-cog mr-1 text-blue-600"></i>
                        Ready with your preferences
                    </p>
                @endif
            </div>
            <div class="flex flex-col sm:flex-row gap-3 w-full md:w-auto">
                <button wire:click="togglePreferences"
                    class="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-2xl border border-gray-200 text-sm font-semibold text-gray-700 hover:border-gray-300">
                    <i class='bx bx-cog text-lg'></i> Preferences
                </button>
                <button wire:click="clearIdeas"
                    class="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-2xl bg-gray-100 text-gray-700 text-sm font-semibold hover:bg-gray-200">
                    <i class='bx bx-trash text-lg'></i> Clear All
                </button>
            </div>
        </div>
    </div>

    <!-- Tabs -->
    <div class="bg-white rounded-3xl shadow-sm border border-gray-100 p-2">
        <div class="flex space-x-1">
            <button wire:click="setTab('generate')"
                class="flex-1 px-4 py-3 text-sm font-medium rounded-2xl transition-all duration-200 cursor-pointer {{ $activeTab === 'generate' ? 'bg-green-50 text-green-700 font-semibold shadow-sm' : 'text-gray-600 hover:bg-gray-50' }}">
                Generate Ideas
            </button>
            <button wire:click="setTab('favorites')" x-on:click="onTabChange()"
                class="flex-1 px-4 py-3 text-sm font-medium rounded-2xl transition-all duration-200 cursor-pointer {{ $activeTab === 'favorites' ? 'bg-green-50 text-green-700 font-semibold shadow-sm' : 'text-gray-600 hover:bg-gray-50' }}">
                Favorites
            </button>
        </div>
    </div>

    <!-- Success/Error Messages -->
    {{-- @if ($successMessage)
        <div class="mb-4 p-4 bg-green-100 border border-green-400 text-green-700 rounded-xl">
            <div class="flex items-center">
                <i class="bx bx-check-circle text-xl mr-2"></i>
                <span>{{ $successMessage }}</span>
            </div>
        </div>
    @endif --}}

    @if ($errorMessage)
        <div class="bg-white rounded-3xl shadow-sm border border-red-200 p-4">
            <div class="flex items-center text-red-700">
                <i class="bx bx-error-circle mr-2"></i>
                <span>{{ $errorMessage }}</span>
            </div>
        </div>
    @endif

    <!-- Preferences Section -->
    @if ($showPreferences)
        <div class="bg-white rounded-3xl shadow-sm border border-gray-100 p-6 md:p-8">
            <div class="mb-6">
                <p class="text-sm uppercase tracking-[0.3em] text-gray-400">Settings</p>
                <h3 class="text-2xl font-semibold text-gray-900 mt-2 flex items-center">
                    <i class="bx bx-cog mr-3 text-green-600"></i>Daily Ideas Preferences
                </h3>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                <div>
                    <label for="pref-topic" class="block text-sm font-semibold text-gray-800 mb-2">Default Topic</label>
                    <input wire:model="topic" type="text" id="pref-topic"
                        class="w-full px-4 py-3 border border-gray-200 rounded-2xl focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm"
                        placeholder="e.g., Digital Marketing, Fitness, Technology">
                </div>
                <div>
                    <label for="pref-niche" class="block text-sm font-semibold text-gray-800 mb-2">Default Niche</label>
                    <input wire:model="niche" type="text" id="pref-niche"
                        class="w-full px-4 py-3 border border-gray-200 rounded-2xl focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm"
                        placeholder="e.g., B2B, Personal Trainer, Startup">
                </div>
            </div>
            <div class="flex flex-col sm:flex-row gap-3">
                <button wire:click="updatePreferences" wire:loading.attr="disabled" wire:target="updatePreferences"
                    class="inline-flex items-center justify-center gap-2 px-6 py-3 bg-green-600 text-white font-semibold rounded-2xl hover:bg-green-500 disabled:opacity-50 transition-colors shadow-lg shadow-green-200">
                    <i class="bx bx-save text-lg"></i>
                    <span wire:loading.remove wire:target="updatePreferences">Save & Generate Ideas</span>
                    <span wire:loading wire:target="updatePreferences">Saving...</span>
                </button>
                <button wire:click="togglePreferences"
                    class="inline-flex items-center justify-center gap-2 px-6 py-3 border border-gray-200 text-gray-700 font-semibold rounded-2xl hover:border-gray-300 transition-colors">
                    Cancel
                </button>
            </div>
        </div>
    @endif

    <!-- Current Settings & Generate Section -->
    @if ($activeTab === 'generate')
        <div class="bg-white rounded-3xl shadow-sm border border-gray-100 p-6 md:p-8">
            <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6">
                <div>
                    <p class="text-sm uppercase tracking-[0.3em] text-gray-400">Current Settings</p>
                    <div class="flex flex-wrap items-center gap-4 mt-2 text-sm text-gray-600">
                        <span class="flex items-center gap-2">
                            <i class="bx bx-tag text-green-600"></i>
                            <strong class="text-gray-800">Topic:</strong> {{ $topic ?: 'Not set' }}
                        </span>
                        <span class="flex items-center gap-2">
                            <i class="bx bx-target-lock text-green-600"></i>
                            <strong class="text-gray-800">Niche:</strong> {{ $niche ?: 'Not set' }}
                        </span>
                    </div>
                </div>
                <button wire:click="togglePreferences"
                    class="inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold text-gray-700 border border-gray-200 rounded-2xl hover:border-gray-300 transition-colors">
                    <i class="bx bx-edit text-lg"></i>
                    Edit
                </button>
            </div>

            <button wire:click="generateIdeas" wire:loading.attr="disabled" wire:target="generateIdeas"
                class="w-full inline-flex items-center justify-center gap-2 px-6 py-3 bg-green-600 text-white font-semibold rounded-2xl hover:bg-green-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors shadow-lg shadow-green-200">
                <i class="bx bx-refresh text-lg"></i>
                <span wire:loading.remove wire:target="generateIdeas">{{ $this->getGenerateButtonText() }}</span>
                <span wire:loading wire:target="generateIdeas">Generating...</span>
            </button>
        </div>
    @endif

    <!-- Generated Ideas -->
    @if ($activeTab === 'generate' && count($ideas) > 0)
        <div class="space-y-6">
            <div class="bg-white rounded-3xl shadow-sm border border-gray-100 p-6">
                <p class="text-sm uppercase tracking-[0.3em] text-gray-400">Generated Ideas</p>
                <h3 class="text-2xl font-semibold text-gray-900 mt-2">{{ count($ideas) }} Ideas Generated</h3>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                @foreach ($ideas as $index => $idea)
                    @php
                        $ideaId = md5($idea);
                    @endphp
                    <div
                        class="bg-white rounded-3xl border border-gray-100 p-6 shadow-sm hover:shadow-md transition-all duration-200">
                        <div class="flex items-start justify-between mb-4">
                            <span
                                class="inline-flex items-center justify-center w-8 h-8 bg-green-50 text-green-600 text-sm font-semibold rounded-2xl">
                                {{ $index + 1 }}
                            </span>
                            <button class="text-amber-500 hover:text-amber-600 transition-colors cursor-pointer"
                                x-on:click="toggleFavoriteFromButton()" data-idea-id="{{ $ideaId }}"
                                data-idea-content="{{ htmlspecialchars($idea, ENT_QUOTES, 'UTF-8') }}">
                                <i class="bx bx-star text-xl"
                                    x-bind:class="isFavorite('{{ $ideaId }}') ? 'bxs-star' : 'bx-star'"></i>
                            </button>
                        </div>
                        <p class="text-gray-700 mb-4 text-sm leading-relaxed"
                            style="display: -webkit-box; -webkit-line-clamp: 8; -webkit-box-orient: vertical; overflow: hidden;">
                            {{ $idea }}</p>
                        <button wire:click="editInChat({{ $index }})" wire:loading.attr="disabled"
                                 wire:target="editInChat"
                                    class="w-full inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold text-green-600 bg-green-50 rounded-2xl hover:bg-green-100 transition-colors">
                                <i class="bx bx-edit text-lg"></i>
                                Edit in Chat
                            </button>
                    </div>
                @endforeach
            </div>


        </div>
         @elseif($activeTab === 'generate' && (count($ideas) === 0 || $loading))
         <div class="text-center py-12 text-gray-500">
             <div class="bg-gray-50 rounded-xl p-8 border border-gray-200">
                 @if($loading || $autoGenerated)
                     <!-- Auto-generation loading state -->
                     <div class="inline-block animate-spin rounded-full h-16 w-16 border-b-4 border-blue-600 mb-6"></div>
                     <h3 class="text-xl font-semibold text-gray-700 mb-4">Generating Your Daily Ideas...</h3>
                     <p class="text-gray-600 mb-4">Creating fresh content based on your preferences</p>
                     <div class="bg-white rounded-xl p-4 border border-gray-200 inline-block">
                         <p class="text-sm text-gray-700">
                             <span class="font-medium text-blue-600">{{ $topic }}</span>
                             for
                             <span class="font-medium text-green-600">{{ $niche }}</span>
                         </p>
                     </div>
                     <p class="text-xs text-gray-500 mt-4">This may take a few moments...</p>
                 @else
                     <!-- Ready state -->
                     <i class="bx bx-lightbulb text-6xl mb-6 text-blue-500"></i>
                     <h3 class="text-xl font-semibold text-gray-700 mb-4">Ready to Generate Ideas!</h3>
                     <p class="text-gray-600 mb-4">Daily ideas will be auto-generated based on your preferences</p>
                     <div class="bg-white rounded-xl p-4 border border-gray-200 inline-block">
                         <p class="text-sm text-gray-700">
                             <span class="font-medium text-blue-600">{{ $topic }}</span>
                             for
                             <span class="font-medium text-green-600">{{ $niche }}</span>
                         </p>
                     </div>
                     <p class="text-xs text-gray-500 mt-4">Ideas will appear here once generated</p>
                 @endif
             </div>
         </div>
     @endif

    <!-- Favorites Tab -->
    @if ($activeTab === 'favorites')
        <div class="space-y-6">
            <div class="bg-white rounded-3xl shadow-sm border border-gray-100 p-6">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-sm uppercase tracking-[0.3em] text-gray-400">Saved Ideas</p>
                        <h3 class="text-2xl font-semibold text-gray-900 mt-2">Favorite Ideas</h3>
                    </div>
                    <button x-on:click="loadFavorites(); renderFavorites();"
                        class="inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold text-gray-700 border border-gray-200 rounded-2xl hover:border-gray-300 transition-colors">
                        <i class="bx bx-refresh text-lg"></i> Refresh
                    </button>
                </div>
            </div>
            <div id="favorites-container" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <!-- Favorites will be loaded here via JavaScript -->
            </div>
            <div id="no-favorites" class="bg-white rounded-3xl shadow-sm border border-gray-100 p-12 text-center" style="display: none;">
                <div class="w-16 h-16 bg-amber-50 rounded-3xl flex items-center justify-center mx-auto mb-6">
                    <i class="bx bx-star text-3xl text-amber-500"></i>
                </div>
                <h3 class="text-xl font-semibold text-gray-900 mb-2">No favorite ideas yet</h3>
                <p class="text-gray-500 text-sm">Star ideas from the Generate Ideas tab to save them here</p>
            </div>
        </div>
    @endif

    <!-- Loading State -->
    @if ($loading)
        <div class="text-center py-8">
            <div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            <p class="mt-2 text-gray-600">Generating ideas...</p>
        </div>
    @endif
</div>

<script>
    function dailyPostIdeas() {
        return {
            favorites: [],
            activeTab: '{{ $activeTab }}',

            init() {
                this.loadFavorites();
                this.renderFavorites();
                // Make instance globally available
                window.dailyPostIdeasInstance = this;
                console.log('DailyPostIdeas initialized, favorites:', this.favorites);

                // Watch for tab changes
                this.$watch('activeTab', (value) => {
                    if (value === 'favorites') {
                        console.log('Active tab changed to favorites');
                        this.loadFavorites();
                        this.renderFavorites();
                    }
                });


            },

            loadFavorites() {
                const stored = localStorage.getItem('dailyPostIdeas_favorites');
                this.favorites = stored ? JSON.parse(stored) : [];
                console.log('Loaded from localStorage:', this.favorites);
            },

            saveFavorites() {
                localStorage.setItem('dailyPostIdeas_favorites', JSON.stringify(this.favorites));
                console.log('Saved to localStorage:', this.favorites);
            },

            toggleFavorite(ideaId, idea) {
                console.log('toggleFavorite called with:', ideaId, idea);
                const existingIndex = this.favorites.findIndex(fav => fav.id === ideaId);

                if (existingIndex >= 0) {
                    // Remove from favorites
                    this.favorites.splice(existingIndex, 1);
                    console.log('Removed from favorites');
                } else {
                    // Add to favorites
                    this.favorites.push({
                        id: ideaId,
                        content: idea,
                        addedAt: new Date().toISOString()
                    });
                    console.log('Added to favorites');
                }

                this.saveFavorites();
                this.renderFavorites();
                console.log('Current favorites:', this.favorites);
            },

            toggleFavoriteFromButton() {
                const ideaId = this.$el.getAttribute('data-idea-id');
                const ideaContent = this.$el.getAttribute('data-idea-content');
                console.log('toggleFavoriteFromButton called with:', ideaId, ideaContent);
                this.toggleFavorite(ideaId, ideaContent);
            },

            isFavorite(ideaId) {
                return this.favorites.some(fav => fav.id === ideaId);
            },

            removeFavorite(ideaId) {
                const index = this.favorites.findIndex(fav => fav.id === ideaId);
                if (index >= 0) {
                    this.favorites.splice(index, 1);
                    this.saveFavorites();
                    this.renderFavorites();
                }
            },

            renderFavorites() {
                console.log('renderFavorites called, favorites:', this.favorites);
                const container = document.getElementById('favorites-container');
                const noFavorites = document.getElementById('no-favorites');

                console.log('Container found:', !!container);
                console.log('No favorites element found:', !!noFavorites);

                if (!container) {
                    console.log('Container not found, returning');
                    return;
                }

                if (this.favorites.length === 0) {
                    console.log('No favorites, showing empty state');
                    container.innerHTML = '';
                    if (noFavorites) noFavorites.style.display = 'block';
                    return;
                }

                console.log('Rendering favorites, count:', this.favorites.length);
                if (noFavorites) noFavorites.style.display = 'none';

                container.innerHTML = this.favorites.map((favorite, index) => `
                 <div class="bg-white rounded-3xl border border-gray-100 p-6 shadow-sm hover:shadow-md transition-all duration-200">
                     <div class="flex items-start justify-between mb-4">
                         <span class="inline-flex items-center justify-center w-8 h-8 bg-amber-50 text-amber-600 text-sm font-semibold rounded-2xl">
                             ${index + 1}
                         </span>
                         <button onclick="window.dailyPostIdeasInstance.removeFavorite('${favorite.id}')" 
                                 class="text-red-500 hover:text-red-600 transition-colors cursor-pointer">
                             <i class="bx bx-trash text-xl"></i>
                         </button>
                     </div>
                     <p class="text-gray-700 mb-4 text-sm leading-relaxed" style="display: -webkit-box; -webkit-line-clamp: 8; -webkit-box-orient: vertical; overflow: hidden;">${favorite.content}</p>
                     <button onclick="window.dailyPostIdeasInstance.editFavoriteInChatFromButton(this)" 
                             data-content="${favorite.content.replace(/"/g, '&quot;')}"
                             class="w-full inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold text-green-600 bg-green-50 rounded-2xl hover:bg-green-100 transition-colors">
                         <i class="bx bx-edit text-lg"></i>
                         Edit in Chat
                     </button>
                 </div>
             `).join('');
            },

            editFavoriteInChat(content) {
                console.log('editFavoriteInChat called with:', content);
                // Dispatch event to ChatComponent
                window.Livewire.dispatch('edit-idea-in-chat', {
                    idea: content
                });
                // Also dispatch event to open chat
                window.Livewire.dispatch('open-chat');
                console.log('Event dispatched to ChatComponent and open-chat triggered');
            },

            editFavoriteInChatFromButton(button) {
                console.log('editFavoriteInChatFromButton called');
                const content = button.getAttribute('data-content');
                console.log('Raw content from data attribute:', content);
                if (content) {
                    // Decode HTML entities
                    const decodedContent = content.replace(/&quot;/g, '"');
                    console.log('Decoded content:', decodedContent);
                    this.editFavoriteInChat(decodedContent);
                } else {
                    console.log('No content found in data attribute');
                }
            },

            // Listen for tab changes
            onTabChange() {
                console.log('Tab changed to favorites, rendering...');
                this.loadFavorites(); // Reload from localStorage
                this.renderFavorites();
            }
        }
    }

    // Listen for Livewire events
    document.addEventListener('livewire:init', () => {
        Livewire.on('render-favorites', () => {
            // Wait a bit for Alpine to be ready
            setTimeout(() => {
                if (window.dailyPostIdeasInstance) {
                    window.dailyPostIdeasInstance.loadFavorites();
                    window.dailyPostIdeasInstance.renderFavorites();
                }
            }, 200);
        });

        // Listen for auto-generation event
        Livewire.on('auto-generate-ideas', () => {
            console.log('Auto-generating ideas after page load...');
            // The component will handle this event automatically via the #[On] attribute
        });

        // Auto-generate ideas after page loads if needed
        document.addEventListener('DOMContentLoaded', function() {
            // Wait for page to fully load, then check if we need to auto-generate
            setTimeout(() => {
                // Check if there are no ideas displayed on the page
                const ideasContainer = document.querySelector('.space-y-4');
                const hasIdeasDisplayed = ideasContainer && ideasContainer.children.length > 0;

                if (!hasIdeasDisplayed) {
                    console.log('No ideas displayed, triggering auto-generation...');
                    // Dispatch the auto-generate event
                    window.Livewire.dispatch('auto-generate-ideas');
                }
            }, 2000); // Wait 2 seconds after page load
        });
    });
</script>
